dist: trusty

language: node_js
node_js:
  - '10'

cache:
  npm: true
  directories:
    - node_modules # NPM packages

env:
  - CI_ENV=travis

install:
  - npm install

script:
  #- commitlint-travis
  - npm run lint
  # - npm run build

deploy:
  provider: script
  skip_cleanup: true
  script: ./deploy.sh
  keep_history: true
