dist: trusty

language: node_js
node_js:
  - '10'

cache:
  npm: true
  directories:
    - node_modules # NPM packages

env:
  - CI_ENV=travis

install:
  - npm install

script:
  - commitlint-travis
  - npm run lint
  - npm run bootstrap

jobs:
  include:
    - stage: deploy docs
      deploy:
        provider: script
        script: ./deploy.sh
        skip_cleanup: true
        keep_history: true
    - stage: npm release
      before_deploy:
        - echo "//registry.npmjs.org/:_authToken=\${NPM_TOKEN}" >> $HOME/.npmrc 2> /dev/null
      deploy:
        provider: script
        script: 'npm run lerna:publish'
        skip_cleanup: true
        keep_history: true
        on:
          tags: true
